name: Hello Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: ["closed"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  name: Krishna
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      name: KK
    steps:
      - name: Run a one-line script
        run: echo Hello, $name!
  pull_requests_only:
    needs: [build]
    runs-on: ubuntu-latest
    if: github..event_name == 'pull_request'
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project. 
          echo hi, $name!
